version: '3.2'
services:
  est-proxy:
    build:
      context: ../../.
      dockerfile: examples/Docker/est_proxy/Dockerfile
    image: est-proxy
    volumes:
      - type: bind
        source: ./data
        target: /usr/local/est_proxy/data
        read_only: false
      - type: bind
        source: /etc/timezone
        target: /etc/timezone
        read_only: true
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
    ports:
      - "17443:17443"
    restart: always

networks:
  default:
    external:
      name: est-proxy
